---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: refactor-agent
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: refactor-agent.service-account-token
  annotations:
    kubernetes.io/service-account.name: refactor-agent
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: refactor-executor
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: refactor-agent-executor
subjects:
  - kind: ServiceAccount
    name: refactor-agent
roleRef:
  kind: Role
  name: refactor-executor
  apiGroup: rbac.authorization.k8s.io
